ComicGallery/ComicGallery/Models/Artists.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComicGallery.Models
{
    public class Artists
    {
        public string Name { get; set; }
        public string Role { get; set; }
    }
}

ComicGallery/ComicGallery/Models/ComicBook.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComicGallery.Models
{
    public class ComicBook
    {
        public int Id { get; set; }
        public string SeriesTitle { get; set; }
        public int IssueNumber { get; set; }
        public string DescriptionHtml { get; set; }
        public Artists[] Artists { get; set; }
        public bool Favorite { get; set; }


        //Remember leaving out the set makes this a readonly property

        //this is the short hand for setting a get or readonly propety
        public string DisplayText => SeriesTitle + " #" + IssueNumber;

        public string CoverImageFileName => SeriesTitle.Replace(" ", "-").ToLower() + "-" + IssueNumber + ".jpg";
    }
}

ComicGallery/ComicGallery/Controllers/ComicGalleryController.cs
using ComicGallery.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ComicGallery.Controllers
{
    public class ComicGalleryController : Controller
    {
        // GET: ComicGallery
        public ActionResult Detail()
        {
            var comicBook = new ComicBook()
            {
                SeriesTitle = "The Amazing Spider-Man!",
                IssueNumber = 700,
                DescriptionHtml = "<p>Final issue! Witness the final hours of Doctor Octopus' " +
                        "life and his one, last, great act of revenge! Even if Spider-Man survives... " +
                        "<strong>will Peter Parker?</strong></p>",
                Artists = new Artists[]
                {
                    new Artists() {Name = "Dan Slott", Role = "Script"},
                    new Artists() {Name = "Humberto Ramos", Role = "Pencils"},
                    new Artists() {Name = "Victor Olazaba", Role = "Inks"},
                    new Artists() {Name = "Edgar Delgado", Role = "Colors"},
                    new Artists() {Name = "Chris Eliopoulos", Role = "Letters"}
                }
            };
            // =========================================================================================================================================

            //WHEN USING VIEWBAG

            //ViewBag.SeriesTitle = "The Amazing SpiderMan";
            //ViewBag.IssueNumber = 700;
            //ViewBag.Artists = new string[]
            //{
            //    "Script: Dan Slott",
            //    "Pencils: Humberto Ramos",
            //    "Inks: Victor Olazaba",
            //    "Colors: Edgar Delgado",
            //    "Letters: Chris Eliopoulos"
            //};
            //ViewBag.Description = "<p>Final issue! Witness the final hours of Doctor Octopus' " +
            //            "life and his one, last, great act of revenge! Even if Spider-Man survives... " +
            //            "<strong>will Peter Parker?</strong></p>";
            // =========================================================================================================================================

            //send the comicBook var to the view to be displayed
            return View(comicBook);
        }
    }
}

ComicGallery/ComicGallery/Views/ComicGallery/Detail.cshtml
@model ComicGallery.Models.ComicBook

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = Model.DisplayText;
}

<h2>@Model.DisplayText</h2>

<div class="row">
    <div class="col-md-6">
        <div class="well">
            <h5><label>Series Title:</label> @Model.SeriesTitle</h5>
            <h5><label>Issue #:</label> @Model.IssueNumber</h5>
            <h5><label>Favorite:</label> @Model.Favorite</h5>

            @if (Model.Artists.Length > 0)
            {
                <h5>Artists:</h5>
                <div>
                    <ul>
                        @foreach (var artists in Model.Artists)
                        {
                            <li>@artists.Role: @artists.Name</li>
                        }
                    </ul>
                </div>
            }
        </div>
        <h5>Description</h5>
        <p>@Model.DescriptionHtml</p>
    </div>
    <div class="col-md-6">
        <img src="/Images/@Model.CoverImageFileName"
             alt="@Model.DisplayText" class="img-responsive" />
    </div>
</div>

ComicGallery/ComicGallery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Comic Gallery", "Index", "ComicGallery", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>